name: Update Mosque Data
on:
  issues:
    types: [opened]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Data from Issue
        id: extract
        run: |
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Parse Town Name
        run: |
          town=$(echo "${ISSUE_BODY}" | grep "**Town:**" | cut -d ' ' -f 2)
          echo "TOWN=$town" >> $GITHUB_ENV

      - name: Extract JSON Data
        run: |
          json_data=$(echo "${ISSUE_BODY}" | awk '/```json/,/```/' | sed '1d;$d')
          echo "$json_data" > "$TOWN.json"

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add "$TOWN.json"
          git commit -m "Update $TOWN.json from web app"
          git push https://x-access-token:$GH_PAT@github.com/vaswin0/mosque-data.git
